import '@/app/globals.css'
import { Analytics } from '@vercel/analytics/react';
import { Merriweather } from 'next/font/google'
import Header from '@/components/sections/Header/Header';

const font = Merriweather({
  subsets: ['latin'],
  display: 'swap',
  weight: ["300","400", "700", "900"]
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const headerData = {
  logo: {
    text: "OCEAN UNIVERSITY",
    src: "",
  },
  nav: [
    {
      title: "Home",
      url: "/"
    },
    {
      title: "About",
      url: "/about"
    },
    {
      title: "Departments",
      url: "/departments"
    },
    {
      title: "Doctors",
      url: "/doctors"
    },
    {
      title: "Contacts",
      url: "/contacts"
    },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header data={headerData} />
        {children}
        <Analytics />
      </body>
    </html>
  )
}